site_name: Kratos Geo Mechanics Application Documentation
site_url: http://127.0.0.1:8000/
theme:
  name: material
  icon:
    annotation: material/arrow-right-circle-outline
  features:
    - content.code.annotate
    - content.code.copy
repo_url: https://github.com/Deltares/Kratos-GeoMechanicsApplication-Documentation/
repo_name: Deltares/Kratos-GeoMechanicsApplication-Documentation/
extra:
  authoremail: kratos@deltares.nl
  annotate:
    json: [.s2]
markdown_extensions:
  - pymdownx.superfences
plugins:
  - macros:
      include_yaml:
        - docs/input_parameters/shared_parameters.yml

copyright: Copyright &copy; 2026 Deltares