site_name: Kratos Geo Mechanics Application Documentation
repo_url: https://github.com/Deltares/Kratos-GeoMechanicsApplication-Documentation/
repo_name: Deltares/Kratos-GeoMechanicsApplication-Documentation/

theme:
  name: material
  favicon: img/favicon.ico
  logo: img/favicon.ico
  palette: 
    # Palette toggle for light mode
    - primary: light blue
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    annotation: material/arrow-right-circle-outline
  features:
    - content.code.annotate
    - content.code.copy
    - toc.integrate

nav:
  - Home: index.md
  - 'getting_started.md'
  - 'theory.md'
  - User Documentation:
      - Overview: 'user_documentation.md'
      - "File Descriptions":
        - input_parameters/material_parameters.md
        - input_parameters/mesh_file_description.md
        - input_parameters/project_parameters.md
  - 'examples_and_tutorials.md'
  - 'validation_and_verification.md'
  - 'developer_documentation.md'
  - 'about.md'

extra:
  authoremail: kratos@deltares.nl
  annotate:
    json: [.s2]
  scope: /

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search
  - macros:
      include_yaml:
        - docs/input_parameters/shared_parameters.yml

copyright: Copyright &copy; 2026 Deltares